name: 'msmarco_PR'
data_folder: 'datasets/ms_marco_subset100/'
train_data: 'SUBSET100train.json'
train_documents: 'documents.json'
dev_data: 'SUBSET100train.json'
dev_documents: 'documents.json'
test_data: 'SUBSET100train.json'
test_documents: 'documents.json'

word2id: 'SUBSET100vocab.txt'
relation2id: 'SUBSET100relations.txt'
entity2id: 'SUBSET100entities_plus_qe.txt'
word_emb_file: null 
entity_emb_file: null 
entity_kge_file: null 
relation_emb_file: null 
relation_kge_file: null 

to_save_model: True
save_model_file: "model/repro/msmarco/subset100docs1265queries_model"
pred_file: "model/repro/msmarco/subset100docs1265queries_preds"
load_model_file: null

# graph options
fact_dropout: 0.0
use_kb: True
use_doc: True

num_layer: 3
max_query_word: 10
max_document_word: 40

entity_dim: 80
word_dim: 80
kge_dim: 80
pagerank_lambda: 0.8
fact_scale: 1
use_inverse_relation: True

# optimization
num_epoch: 5
gradient_clip: 1
learning_rate: 0.01
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False

train_batch_size: 6
testndev_batch_size: 6
